import logging

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

from ..services.redis_service import get_debate, parse_debate_id, resolve_debate_id

logger = logging.getLogger(__name__)

router = APIRouter()

NOT_FOUND_CLOSE_CODE = 4404


@router.websocket("/ws/debate/{debate_id}")
async def debate_ws(websocket: WebSocket, debate_id: str):
    """Replay a stored debate stage by stage.

    Debates are generated by the daily job (or the protected admin endpoint), never
    by a browser connection, so opening a page can't trigger paid LLM calls.
    """
    await websocket.accept()
    resolved = await resolve_debate_id(debate_id)
    parsed = parse_debate_id(resolved) if resolved else None
    debate = await get_debate(*parsed) if parsed else None
    if not resolved or not debate:
        await websocket.send_json({"error": "not_found", "message": "No debate found for this id."})
        await websocket.close(code=NOT_FOUND_CLOSE_CODE)
        return

    base = {"debate_id": resolved, "topic": debate["topic"]}
    try:
        await websocket.send_json({
            **base, "node": "replay", "status": "debating",
            "data": debate["arguments"], "rebuttals": {}, "verdict": "", "bias_scores": {},
        })
        await websocket.send_json({
            **base, "node": "replay", "status": "rebuttal",
            "data": debate["arguments"], "rebuttals": debate["rebuttals"], "verdict": "", "bias_scores": {},
        })
        await websocket.send_json({
            **base, "node": "replay", "status": "done",
            "data": debate["arguments"], "rebuttals": debate["rebuttals"],
            "verdict": debate["verdict"], "bias_scores": debate["bias_scores"],
        })
        await websocket.close()
    except WebSocketDisconnect:
        pass
